---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  flake8

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    cgroupns_mode: host
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
  inventory:
    group_vars:
      python3:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: latest
verifier:
  name: testinfra
