---
- name: Prepare
  hosts: all
  gather_facts: true
  vars:
    promtail_version: "2.7.3"
    promtail_binary_local_dir: "/tmp"
    go_arch_map:
      x86_64: 'amd64'
      aarch64: 'arm64'
      armv7l: 'arm'
      armv6l: 'arm'
    go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"
  
  tasks:
    - name: Ensure that net-tools is available
      package:
        name: net-tools
        state: present
      when: ansible_os_family == 'RedHat'
    - name: Download zip archive on controler
      get_url:
        url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-{{ go_arch }}.zip"
        dest: "/tmp/{{ promtail_version }}_promtail-linux-{{ go_arch }}.zip"
        force: True
      delegate_to: localhost
